/****************************************************************************
 *   Copyright (c) 2020 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_DIALOG_DLGSETTINGSDRAWSTYLES_H
#define GUI_DIALOG_DLGSETTINGSDRAWSTYLES_H

/*[[[cog
import DlgSettingsDrawStyles
DlgSettingsDrawStyles.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:399)
#include <Gui/PropertyPage.h>
#include <Gui/PrefWidgets.h>
// Auto generated code (Tools/params_utils.py:404)
class QLabel;
class QGroupBox;

namespace Gui {
namespace Dialog {
/** Preference dialog for various draw styles related settings

 * This class is auto generated by DlgSettingsDrawStyles.py. Modify that file
 * instead of this one, if you want to make any change. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r DlgSettingsDrawStyles.h DlgSettingsDrawStyles.cpp
 * @endcode
 */
class DlgSettingsDrawStyles : public Gui::Dialog::PreferencePage
{
    Q_OBJECT

public:
    DlgSettingsDrawStyles( QWidget* parent = 0 );
    ~DlgSettingsDrawStyles();

    void saveSettings();
    void loadSettings();
    void retranslateUi();

protected:
    void changeEvent(QEvent *e);

private:

    // Auto generated code (Tools/params_utils.py:323)
    QGroupBox * groupDocument = nullptr;
    QLabel *labelDefaultDrawStyle = nullptr;
    Gui::PrefComboBox *DefaultDrawStyle = nullptr;

    // Auto generated code (Tools/params_utils.py:323)
    QGroupBox * groupSelection = nullptr;
    QLabel *labelTransparencyOnTop = nullptr;
    Gui::PrefDoubleSpinBox *TransparencyOnTop = nullptr;
    QLabel *labelSelectionLineThicken = nullptr;
    Gui::PrefDoubleSpinBox *SelectionLineThicken = nullptr;
    QLabel *labelSelectionLineMaxWidth = nullptr;
    Gui::PrefDoubleSpinBox *SelectionLineMaxWidth = nullptr;
    QLabel *labelSelectionPointScale = nullptr;
    Gui::PrefDoubleSpinBox *SelectionPointScale = nullptr;
    QLabel *labelSelectionPointMaxSize = nullptr;
    Gui::PrefDoubleSpinBox *SelectionPointMaxSize = nullptr;
    QLabel *labelSelectionLinePattern = nullptr;
    Gui::PrefLinePattern *SelectionLinePattern = nullptr;
    QLabel *labelSelectionLinePatternScale = nullptr;
    Gui::PrefSpinBox *SelectionLinePatternScale = nullptr;
    QLabel *labelSelectionHiddenLineWidth = nullptr;
    Gui::PrefDoubleSpinBox *SelectionHiddenLineWidth = nullptr;

    // Auto generated code (Tools/params_utils.py:323)
    QGroupBox * groupHiddenLines = nullptr;
    Gui::PrefCheckBox *HiddenLineOverrideFaceColor = nullptr;
    Gui::PrefColorButton *HiddenLineFaceColor = nullptr;
    Gui::PrefCheckBox *HiddenLineOverrideColor = nullptr;
    Gui::PrefColorButton *HiddenLineColor = nullptr;
    Gui::PrefCheckBox *HiddenLineOverrideBackground = nullptr;
    Gui::PrefColorButton *HiddenLineBackground = nullptr;
    Gui::PrefCheckBox *HiddenLineShaded = nullptr;
    Gui::PrefCheckBox *HiddenLineShowOutline = nullptr;
    Gui::PrefCheckBox *HiddenLinePerFaceOutline = nullptr;
    Gui::PrefCheckBox *HiddenLineHideFace = nullptr;
    Gui::PrefCheckBox *HiddenLineHideSeam = nullptr;
    Gui::PrefCheckBox *HiddenLineHideVertex = nullptr;
    Gui::PrefCheckBox *HiddenLineOverrideTransparency = nullptr;
    Gui::PrefDoubleSpinBox *HiddenLineTransparency = nullptr;
    QLabel *labelHiddenLineWidth = nullptr;
    Gui::PrefDoubleSpinBox *HiddenLineWidth = nullptr;
    QLabel *labelHiddenLinePointSize = nullptr;
    Gui::PrefDoubleSpinBox *HiddenLinePointSize = nullptr;

    // Auto generated code (Tools/params_utils.py:323)
    QGroupBox * groupShadow = nullptr;
    Gui::PrefCheckBox *ShadowSpotLight = nullptr;
    QLabel *labelShadowLightColor = nullptr;
    Gui::PrefColorButton *ShadowLightColor = nullptr;
    QLabel *labelShadowLightIntensity = nullptr;
    Gui::PrefDoubleSpinBox *ShadowLightIntensity = nullptr;
    Gui::PrefCheckBox *ShadowShowGround = nullptr;
    Gui::PrefCheckBox *ShadowGroundBackFaceCull = nullptr;
    QLabel *labelShadowGroundColor = nullptr;
    Gui::PrefColorButton *ShadowGroundColor = nullptr;
    QLabel *labelShadowGroundScale = nullptr;
    Gui::PrefDoubleSpinBox *ShadowGroundScale = nullptr;
    QLabel *labelShadowGroundTransparency = nullptr;
    Gui::PrefDoubleSpinBox *ShadowGroundTransparency = nullptr;
    QLabel *labelShadowGroundTexture = nullptr;
    Gui::PrefFileChooser *ShadowGroundTexture = nullptr;
    QLabel *labelShadowGroundTextureSize = nullptr;
    Gui::PrefDoubleSpinBox *ShadowGroundTextureSize = nullptr;
    QLabel *labelShadowGroundBumpMap = nullptr;
    Gui::PrefFileChooser *ShadowGroundBumpMap = nullptr;
    Gui::PrefCheckBox *ShadowGroundShading = nullptr;
    Gui::PrefCheckBox *ShadowUpdateGround = nullptr;
    QLabel *labelShadowDisplayMode = nullptr;
    Gui::PrefComboBox *ShadowDisplayMode = nullptr;
    QLabel *labelShadowPrecision = nullptr;
    Gui::PrefDoubleSpinBox *ShadowPrecision = nullptr;
    QLabel *labelShadowSmoothBorder = nullptr;
    Gui::PrefSpinBox *ShadowSmoothBorder = nullptr;
    QLabel *labelShadowSpreadSize = nullptr;
    Gui::PrefSpinBox *ShadowSpreadSize = nullptr;
    QLabel *labelShadowSpreadSampleSize = nullptr;
    Gui::PrefSpinBox *ShadowSpreadSampleSize = nullptr;
    QLabel *labelShadowEpsilon = nullptr;
    Gui::PrefDoubleSpinBox *ShadowEpsilon = nullptr;
    QLabel *labelShadowThreshold = nullptr;
    Gui::PrefDoubleSpinBox *ShadowThreshold = nullptr;
    QLabel *labelShadowBoundBoxScale = nullptr;
    Gui::PrefDoubleSpinBox *ShadowBoundBoxScale = nullptr;
    QLabel *labelShadowMaxDistance = nullptr;
    Gui::PrefDoubleSpinBox *ShadowMaxDistance = nullptr;
    Gui::PrefCheckBox *ShadowTransparentShadow = nullptr;
// Auto generated code (Tools/params_utils.py:449)
};
} // namespace Dialog
} // namespace Gui
//[[[end]]]

#endif // GUI_DIALOG_DLGSETTINGSDRAWSTYLES_H
