/****************************************************************************
 *   Copyright (c) 2020 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_DIALOG_DLGSETTINGSDRAWSTYLES_H
#define GUI_DIALOG_DLGSETTINGSDRAWSTYLES_H

/*[[[cog
import DlgSettingsDrawStyles
DlgSettingsDrawStyles.declare()
]]]*/

// Auto generated code (Tools/params_utils.py:374)
#include <Gui/PropertyPage.h>
#include <Gui/PrefWidgets.h>
// Auto generated code (Tools/params_utils.py:379)
class QLabel;
class QGroupBox;

namespace Gui {
namespace Dialog {
/** Preference dialog for various draw styles related settings

 * This class is auto generated by DlgSettingsDrawStyles.py. Modify that file
 * instead of this one, if you want to make any change. You need
 * to install Cog Python package for code generation:
 * @code
 *     pip install cogapp
 * @endcode
 *
 * Once modified, you can regenerate the header and the source file,
 * @code
 *     python3 -m cogapp -r DlgSettingsDrawStyles.h DlgSettingsDrawStyles.cpp
 * @endcode
 */
class DlgSettingsDrawStyles : public Gui::Dialog::PreferencePage
{
    Q_OBJECT

public:
    DlgSettingsDrawStyles( QWidget* parent = 0 );
    ~DlgSettingsDrawStyles();

    void saveSettings();
    void loadSettings();
    void retranslateUi();

protected:
    void changeEvent(QEvent *e);

private:

    // Auto generated code (Tools/params_utils.py:299)
    QGroupBox * groupSelection = nullptr;
    QLabel *labelTransparencyOnTop = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxTransparencyOnTop = nullptr;
    QLabel *labelSelectionLineThicken = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxSelectionLineThicken = nullptr;
    QLabel *labelSelectionLineMaxWidth = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxSelectionLineMaxWidth = nullptr;
    QLabel *labelSelectionPointScale = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxSelectionPointScale = nullptr;
    QLabel *labelSelectionPointMaxSize = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxSelectionPointMaxSize = nullptr;
    QLabel *labelSelectionLinePattern = nullptr;
    Gui::PrefLinePattern *linePatternSelectionLinePattern = nullptr;
    QLabel *labelSelectionLinePatternScale = nullptr;
    Gui::PrefSpinBox *spinBoxSelectionLinePatternScale = nullptr;
    QLabel *labelSelectionHiddenLineWidth = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxSelectionHiddenLineWidth = nullptr;

    // Auto generated code (Tools/params_utils.py:299)
    QGroupBox * groupHiddenLines = nullptr;
    Gui::PrefCheckBox *checkBoxHiddenLineOverrideFaceColor = nullptr;
    Gui::PrefColorButton *colorButtonHiddenLineFaceColor = nullptr;
    Gui::PrefCheckBox *checkBoxHiddenLineOverrideColor = nullptr;
    Gui::PrefColorButton *colorButtonHiddenLineColor = nullptr;
    Gui::PrefCheckBox *checkBoxHiddenLineOverrideBackground = nullptr;
    Gui::PrefColorButton *colorButtonHiddenLineBackground = nullptr;
    Gui::PrefCheckBox *checkBoxHiddenLineShaded = nullptr;
    Gui::PrefCheckBox *checkBoxHiddenLineShowOutline = nullptr;
    Gui::PrefCheckBox *checkBoxHiddenLinePerFaceOutline = nullptr;
    Gui::PrefCheckBox *checkBoxHiddenLineHideFace = nullptr;
    Gui::PrefCheckBox *checkBoxHiddenLineHideSeam = nullptr;
    Gui::PrefCheckBox *checkBoxHiddenLineHideVertex = nullptr;
    Gui::PrefCheckBox *checkBoxHiddenLineOverrideTransparency = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxHiddenLineTransparency = nullptr;
    QLabel *labelHiddenLineWidth = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxHiddenLineWidth = nullptr;
    QLabel *labelHiddenLinePointSize = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxHiddenLinePointSize = nullptr;

    // Auto generated code (Tools/params_utils.py:299)
    QGroupBox * groupShadow = nullptr;
    Gui::PrefCheckBox *checkBoxShadowSpotLight = nullptr;
    QLabel *labelShadowLightColor = nullptr;
    Gui::PrefColorButton *colorButtonShadowLightColor = nullptr;
    QLabel *labelShadowLightIntensity = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxShadowLightIntensity = nullptr;
    Gui::PrefCheckBox *checkBoxShadowShowGround = nullptr;
    Gui::PrefCheckBox *checkBoxShadowGroundBackFaceCull = nullptr;
    QLabel *labelShadowGroundColor = nullptr;
    Gui::PrefColorButton *colorButtonShadowGroundColor = nullptr;
    QLabel *labelShadowGroundScale = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxShadowGroundScale = nullptr;
    QLabel *labelShadowGroundTransparency = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxShadowGroundTransparency = nullptr;
    QLabel *labelShadowGroundTexture = nullptr;
    Gui::PrefFileChooser *fileChooserShadowGroundTexture = nullptr;
    QLabel *labelShadowGroundTextureSize = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxShadowGroundTextureSize = nullptr;
    QLabel *labelShadowGroundBumpMap = nullptr;
    Gui::PrefFileChooser *fileChooserShadowGroundBumpMap = nullptr;
    Gui::PrefCheckBox *checkBoxShadowGroundShading = nullptr;
    Gui::PrefCheckBox *checkBoxShadowUpdateGround = nullptr;
    QLabel *labelShadowDisplayMode = nullptr;
    Gui::PrefComboBox *comboBoxShadowDisplayMode = nullptr;
    QLabel *labelShadowPrecision = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxShadowPrecision = nullptr;
    QLabel *labelShadowSmoothBorder = nullptr;
    Gui::PrefSpinBox *spinBoxShadowSmoothBorder = nullptr;
    QLabel *labelShadowSpreadSize = nullptr;
    Gui::PrefSpinBox *spinBoxShadowSpreadSize = nullptr;
    QLabel *labelShadowSpreadSampleSize = nullptr;
    Gui::PrefSpinBox *spinBoxShadowSpreadSampleSize = nullptr;
    QLabel *labelShadowEpsilon = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxShadowEpsilon = nullptr;
    QLabel *labelShadowThreshold = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxShadowThreshold = nullptr;
    QLabel *labelShadowBoundBoxScale = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxShadowBoundBoxScale = nullptr;
    QLabel *labelShadowMaxDistance = nullptr;
    Gui::PrefDoubleSpinBox *spinBoxShadowMaxDistance = nullptr;
    Gui::PrefCheckBox *checkBoxShadowTransparentShadow = nullptr;
// Auto generated code (Tools/params_utils.py:424)
};
} // namespace {dialog_namespace}
} // namespace {namespace}
//[[[end]]]

#endif // GUI_DIALOG_DLGSETTINGSDRAWSTYLES_H
