/****************************************************************************
 *   Copyright (c) 2018 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_VIEW_PARAMS_H
#define GUI_VIEW_PARAMS_H

#ifdef FC_OS_MACOSX
#   define FC_ENABLE_MENUBAR_CHECKBOX false
#else
#   define FC_ENABLE_MENUBAR_CHECKBOX true
#endif

/*[[[cog
import ViewParams
ViewParams.declare_begin()
]]]*/

#include <Base/Parameter.h>

namespace Gui {
/** Convenient class to obtain view provider related parameters

* The parameters are under group "User parameter:BaseApp/Preferences/View"
*
* This class is auto generated by ViewParams.py. Modify that file
* instead of this one, if you want to add any parameter. You need
* to install Cog Python package for code generation:
* @code
*     pip install cogapp
* @endcode
*
* Once modified, you can regenerate the header and the source file,
* @code
*     python3 -m cogapp -r ViewParams.h ViewParams.cpp'
* @endcode
*
* You can add a new parameter by adding lines in ViewParams.py. Available
* parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
* a new Int type parameter,
* @code
*     ParamInt(parameter_name, default_value, documentation, on_change=False)
* @endcode
*
* If there is special handling on parameter change, pass in on_change=True.
* And you need to provide a function implementation in ViewParams.cpp with
* the following signature.
 * @code
 *     void ViewParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport ViewParams {
public:
    static ParameterGrp::handle getHandle();

    static const bool & UseNewSelection();
    static const bool & defaultUseNewSelection();
    static void removeUseNewSelection();
    static void setUseNewSelection(const bool &v);
    static const char *docUseNewSelection();

    static const bool & UseSelectionRoot();
    static const bool & defaultUseSelectionRoot();
    static void removeUseSelectionRoot();
    static void setUseSelectionRoot(const bool &v);
    static const char *docUseSelectionRoot();

    static const bool & EnableSelection();
    static const bool & defaultEnableSelection();
    static void removeEnableSelection();
    static void setEnableSelection(const bool &v);
    static const char *docEnableSelection();

    static const bool & EnablePreselection();
    static const bool & defaultEnablePreselection();
    static void removeEnablePreselection();
    static void setEnablePreselection(const bool &v);
    static const char *docEnablePreselection();

    static const long & RenderCache();
    static const long & defaultRenderCache();
    static void removeRenderCache();
    static void setRenderCache(const long &v);
    static const char *docRenderCache();

    static void onRenderCacheChanged();

    static const bool & RandomColor();
    static const bool & defaultRandomColor();
    static void removeRandomColor();
    static void setRandomColor(const bool &v);
    static const char *docRandomColor();

    static const unsigned long & BoundingBoxColor();
    static const unsigned long & defaultBoundingBoxColor();
    static void removeBoundingBoxColor();
    static void setBoundingBoxColor(const unsigned long &v);
    static const char *docBoundingBoxColor();

    static const unsigned long & AnnotationTextColor();
    static const unsigned long & defaultAnnotationTextColor();
    static void removeAnnotationTextColor();
    static void setAnnotationTextColor(const unsigned long &v);
    static const char *docAnnotationTextColor();

    static const unsigned long & HighlightColor();
    static const unsigned long & defaultHighlightColor();
    static void removeHighlightColor();
    static void setHighlightColor(const unsigned long &v);
    static const char *docHighlightColor();

    static const unsigned long & SelectionColor();
    static const unsigned long & defaultSelectionColor();
    static void removeSelectionColor();
    static void setSelectionColor(const unsigned long &v);
    static const char *docSelectionColor();

    static const long & MarkerSize();
    static const long & defaultMarkerSize();
    static void removeMarkerSize();
    static void setMarkerSize(const long &v);
    static const char *docMarkerSize();

    static const unsigned long & DefaultLinkColor();
    static const unsigned long & defaultDefaultLinkColor();
    static void removeDefaultLinkColor();
    static void setDefaultLinkColor(const unsigned long &v);
    static const char *docDefaultLinkColor();

    static const unsigned long & DefaultShapeLineColor();
    static const unsigned long & defaultDefaultShapeLineColor();
    static void removeDefaultShapeLineColor();
    static void setDefaultShapeLineColor(const unsigned long &v);
    static const char *docDefaultShapeLineColor();

    static const unsigned long & DefaultShapeVertexColor();
    static const unsigned long & defaultDefaultShapeVertexColor();
    static void removeDefaultShapeVertexColor();
    static void setDefaultShapeVertexColor(const unsigned long &v);
    static const char *docDefaultShapeVertexColor();

    static const unsigned long & DefaultShapeColor();
    static const unsigned long & defaultDefaultShapeColor();
    static void removeDefaultShapeColor();
    static void setDefaultShapeColor(const unsigned long &v);
    static const char *docDefaultShapeColor();

    static const long & DefaultShapeLineWidth();
    static const long & defaultDefaultShapeLineWidth();
    static void removeDefaultShapeLineWidth();
    static void setDefaultShapeLineWidth(const long &v);
    static const char *docDefaultShapeLineWidth();

    static const long & DefaultShapePointSize();
    static const long & defaultDefaultShapePointSize();
    static void removeDefaultShapePointSize();
    static void setDefaultShapePointSize(const long &v);
    static const char *docDefaultShapePointSize();

    static const bool & CoinCycleCheck();
    static const bool & defaultCoinCycleCheck();
    static void removeCoinCycleCheck();
    static void setCoinCycleCheck(const bool &v);
    static const char *docCoinCycleCheck();

    static const bool & EnablePropertyViewForInactiveDocument();
    static const bool & defaultEnablePropertyViewForInactiveDocument();
    static void removeEnablePropertyViewForInactiveDocument();
    static void setEnablePropertyViewForInactiveDocument(const bool &v);
    static const char *docEnablePropertyViewForInactiveDocument();

    static const bool & ShowSelectionBoundingBox();
    static const bool & defaultShowSelectionBoundingBox();
    static void removeShowSelectionBoundingBox();
    static void setShowSelectionBoundingBox(const bool &v);
    static const char *docShowSelectionBoundingBox();

    static const long & ShowSelectionBoundingBoxThreshold();
    static const long & defaultShowSelectionBoundingBoxThreshold();
    static void removeShowSelectionBoundingBoxThreshold();
    static void setShowSelectionBoundingBoxThreshold(const long &v);
    static const char *docShowSelectionBoundingBoxThreshold();

    static const bool & UpdateSelectionVisual();
    static const bool & defaultUpdateSelectionVisual();
    static void removeUpdateSelectionVisual();
    static void setUpdateSelectionVisual(const bool &v);
    static const char *docUpdateSelectionVisual();

    static const bool & LinkChildrenDirect();
    static const bool & defaultLinkChildrenDirect();
    static void removeLinkChildrenDirect();
    static void setLinkChildrenDirect(const bool &v);
    static const char *docLinkChildrenDirect();

    static const bool & ShowSelectionOnTop();
    static const bool & defaultShowSelectionOnTop();
    static void removeShowSelectionOnTop();
    static void setShowSelectionOnTop(const bool &v);
    static const char *docShowSelectionOnTop();

    static void onShowSelectionOnTopChanged();

    static const bool & ShowPreSelectedFaceOnTop();
    static const bool & defaultShowPreSelectedFaceOnTop();
    static void removeShowPreSelectedFaceOnTop();
    static void setShowPreSelectedFaceOnTop(const bool &v);
    static const char *docShowPreSelectedFaceOnTop();

    static const bool & ShowPreSelectedFaceOutline();
    static const bool & defaultShowPreSelectedFaceOutline();
    static void removeShowPreSelectedFaceOutline();
    static void setShowPreSelectedFaceOutline(const bool &v);
    static const char *docShowPreSelectedFaceOutline();

    static const bool & AutoTransparentPick();
    static const bool & defaultAutoTransparentPick();
    static void removeAutoTransparentPick();
    static void setAutoTransparentPick(const bool &v);
    static const char *docAutoTransparentPick();

    static const bool & SelectElementOnTop();
    static const bool & defaultSelectElementOnTop();
    static void removeSelectElementOnTop();
    static void setSelectElementOnTop(const bool &v);
    static const char *docSelectElementOnTop();

    static const double & TransparencyOnTop();
    static const double & defaultTransparencyOnTop();
    static void removeTransparencyOnTop();
    static void setTransparencyOnTop(const double &v);
    static const char *docTransparencyOnTop();

    static const bool & HiddenLineSelectionOnTop();
    static const bool & defaultHiddenLineSelectionOnTop();
    static void removeHiddenLineSelectionOnTop();
    static void setHiddenLineSelectionOnTop(const bool &v);
    static const char *docHiddenLineSelectionOnTop();

    static const bool & PartialHighlightOnFullSelect();
    static const bool & defaultPartialHighlightOnFullSelect();
    static void removePartialHighlightOnFullSelect();
    static void setPartialHighlightOnFullSelect(const bool &v);
    static const char *docPartialHighlightOnFullSelect();

    static const double & SelectionLineThicken();
    static const double & defaultSelectionLineThicken();
    static void removeSelectionLineThicken();
    static void setSelectionLineThicken(const double &v);
    static const char *docSelectionLineThicken();

    static const double & SelectionLineMaxWidth();
    static const double & defaultSelectionLineMaxWidth();
    static void removeSelectionLineMaxWidth();
    static void setSelectionLineMaxWidth(const double &v);
    static const char *docSelectionLineMaxWidth();

    static const double & SelectionPointScale();
    static const double & defaultSelectionPointScale();
    static void removeSelectionPointScale();
    static void setSelectionPointScale(const double &v);
    static const char *docSelectionPointScale();

    static const double & SelectionPointMaxSize();
    static const double & defaultSelectionPointMaxSize();
    static void removeSelectionPointMaxSize();
    static void setSelectionPointMaxSize(const double &v);
    static const char *docSelectionPointMaxSize();

    static const double & PickRadius();
    static const double & defaultPickRadius();
    static void removePickRadius();
    static void setPickRadius(const double &v);
    static const char *docPickRadius();

    static const double & SelectionTransparency();
    static const double & defaultSelectionTransparency();
    static void removeSelectionTransparency();
    static void setSelectionTransparency(const double &v);
    static const char *docSelectionTransparency();

    static const long & SelectionLinePattern();
    static const long & defaultSelectionLinePattern();
    static void removeSelectionLinePattern();
    static void setSelectionLinePattern(const long &v);
    static const char *docSelectionLinePattern();

    static const long & SelectionLinePatternScale();
    static const long & defaultSelectionLinePatternScale();
    static void removeSelectionLinePatternScale();
    static void setSelectionLinePatternScale(const long &v);
    static const char *docSelectionLinePatternScale();

    static const double & SelectionHiddenLineWidth();
    static const double & defaultSelectionHiddenLineWidth();
    static void removeSelectionHiddenLineWidth();
    static void setSelectionHiddenLineWidth(const double &v);
    static const char *docSelectionHiddenLineWidth();

    static const double & SelectionBBoxLineWidth();
    static const double & defaultSelectionBBoxLineWidth();
    static void removeSelectionBBoxLineWidth();
    static void setSelectionBBoxLineWidth(const double &v);
    static const char *docSelectionBBoxLineWidth();

    static const bool & ShowHighlightEdgeOnly();
    static const bool & defaultShowHighlightEdgeOnly();
    static void removeShowHighlightEdgeOnly();
    static void setShowHighlightEdgeOnly(const bool &v);
    static const char *docShowHighlightEdgeOnly();

    static const double & PreSelectionDelay();
    static const double & defaultPreSelectionDelay();
    static void removePreSelectionDelay();
    static void setPreSelectionDelay(const double &v);
    static const char *docPreSelectionDelay();

    static const bool & UseNewRayPick();
    static const bool & defaultUseNewRayPick();
    static void removeUseNewRayPick();
    static void setUseNewRayPick(const bool &v);
    static const char *docUseNewRayPick();

    static const double & ViewSelectionExtendFactor();
    static const double & defaultViewSelectionExtendFactor();
    static void removeViewSelectionExtendFactor();
    static void setViewSelectionExtendFactor(const double &v);
    static const char *docViewSelectionExtendFactor();

    static const bool & UseTightBoundingBox();
    static const bool & defaultUseTightBoundingBox();
    static void removeUseTightBoundingBox();
    static void setUseTightBoundingBox(const bool &v);
    static const char *docUseTightBoundingBox();

    static const bool & UseBoundingBoxCache();
    static const bool & defaultUseBoundingBoxCache();
    static void removeUseBoundingBoxCache();
    static void setUseBoundingBoxCache(const bool &v);
    static const char *docUseBoundingBoxCache();

    static const bool & RenderProjectedBBox();
    static const bool & defaultRenderProjectedBBox();
    static void removeRenderProjectedBBox();
    static void setRenderProjectedBBox(const bool &v);
    static const char *docRenderProjectedBBox();

    static const bool & SelectionFaceWire();
    static const bool & defaultSelectionFaceWire();
    static void removeSelectionFaceWire();
    static void setSelectionFaceWire(const bool &v);
    static const char *docSelectionFaceWire();

    static const double & NewDocumentCameraScale();
    static const double & defaultNewDocumentCameraScale();
    static void removeNewDocumentCameraScale();
    static void setNewDocumentCameraScale(const double &v);
    static const char *docNewDocumentCameraScale();

    static const long & MaxOnTopSelections();
    static const long & defaultMaxOnTopSelections();
    static void removeMaxOnTopSelections();
    static void setMaxOnTopSelections(const long &v);
    static const char *docMaxOnTopSelections();

    static const bool & MapChildrenPlacement();
    static const bool & defaultMapChildrenPlacement();
    static void removeMapChildrenPlacement();
    static void setMapChildrenPlacement(const bool &v);
    static const char *docMapChildrenPlacement();

    static void onMapChildrenPlacementChanged();

    static const long & CornerNaviCube();
    static const long & defaultCornerNaviCube();
    static void removeCornerNaviCube();
    static void setCornerNaviCube(const long &v);
    static const char *docCornerNaviCube();

    static void onCornerNaviCubeChanged();

    static const bool & NaviRotateToNearest();
    static const bool & defaultNaviRotateToNearest();
    static void removeNaviRotateToNearest();
    static void setNaviRotateToNearest(const bool &v);
    static const char *docNaviRotateToNearest();

    static const long & NaviStepByTurn();
    static const long & defaultNaviStepByTurn();
    static void removeNaviStepByTurn();
    static void setNaviStepByTurn(const long &v);
    static const char *docNaviStepByTurn();

    static const bool & DockOverlayAutoView();
    static const bool & defaultDockOverlayAutoView();
    static void removeDockOverlayAutoView();
    static void setDockOverlayAutoView(const bool &v);
    static const char *docDockOverlayAutoView();

    static void onDockOverlayAutoViewChanged();

    static const bool & DockOverlayExtraState();
    static const bool & defaultDockOverlayExtraState();
    static void removeDockOverlayExtraState();
    static void setDockOverlayExtraState(const bool &v);
    static const char *docDockOverlayExtraState();

    static void onDockOverlayExtraStateChanged();

    static const long & DockOverlayDelay();
    static const long & defaultDockOverlayDelay();
    static void removeDockOverlayDelay();
    static void setDockOverlayDelay(const long &v);
    static const char *docDockOverlayDelay();

    static const long & DockOverlayRevealDelay();
    static const long & defaultDockOverlayRevealDelay();
    static void removeDockOverlayRevealDelay();
    static void setDockOverlayRevealDelay(const long &v);
    static const char *docDockOverlayRevealDelay();

    static const long & DockOverlaySplitterHandleTimeout();
    static const long & defaultDockOverlaySplitterHandleTimeout();
    static void removeDockOverlaySplitterHandleTimeout();
    static void setDockOverlaySplitterHandleTimeout(const long &v);
    static const char *docDockOverlaySplitterHandleTimeout();

    static const bool & DockOverlayActivateOnHover();
    static const bool & defaultDockOverlayActivateOnHover();
    static void removeDockOverlayActivateOnHover();
    static void setDockOverlayActivateOnHover(const bool &v);
    static const char *docDockOverlayActivateOnHover();

    static const bool & DockOverlayAutoMouseThrough();
    static const bool & defaultDockOverlayAutoMouseThrough();
    static void removeDockOverlayAutoMouseThrough();
    static void setDockOverlayAutoMouseThrough(const bool &v);
    static const char *docDockOverlayAutoMouseThrough();

    static const bool & DockOverlayWheelPassThrough();
    static const bool & defaultDockOverlayWheelPassThrough();
    static void removeDockOverlayWheelPassThrough();
    static void setDockOverlayWheelPassThrough(const bool &v);
    static const char *docDockOverlayWheelPassThrough();

    static const long & DockOverlayWheelDelay();
    static const long & defaultDockOverlayWheelDelay();
    static void removeDockOverlayWheelDelay();
    static void setDockOverlayWheelDelay(const long &v);
    static const char *docDockOverlayWheelDelay();

    static const long & DockOverlayAlphaRadius();
    static const long & defaultDockOverlayAlphaRadius();
    static void removeDockOverlayAlphaRadius();
    static void setDockOverlayAlphaRadius(const long &v);
    static const char *docDockOverlayAlphaRadius();

    static const bool & DockOverlayCheckNaviCube();
    static const bool & defaultDockOverlayCheckNaviCube();
    static void removeDockOverlayCheckNaviCube();
    static void setDockOverlayCheckNaviCube(const bool &v);
    static const char *docDockOverlayCheckNaviCube();

    static void onDockOverlayCheckNaviCubeChanged();

    static const long & DockOverlayHintTriggerSize();
    static const long & defaultDockOverlayHintTriggerSize();
    static void removeDockOverlayHintTriggerSize();
    static void setDockOverlayHintTriggerSize(const long &v);
    static const char *docDockOverlayHintTriggerSize();

    static const long & DockOverlayHintSize();
    static const long & defaultDockOverlayHintSize();
    static void removeDockOverlayHintSize();
    static void setDockOverlayHintSize(const long &v);
    static const char *docDockOverlayHintSize();

    static const bool & DockOverlayHintTabBar();
    static const bool & defaultDockOverlayHintTabBar();
    static void removeDockOverlayHintTabBar();
    static void setDockOverlayHintTabBar(const bool &v);
    static const char *docDockOverlayHintTabBar();

    static const bool & DockOverlayHideTabBar();
    static const bool & defaultDockOverlayHideTabBar();
    static void removeDockOverlayHideTabBar();
    static void setDockOverlayHideTabBar(const bool &v);
    static const char *docDockOverlayHideTabBar();

    static void onDockOverlayHideTabBarChanged();

    static const long & DockOverlayHintDelay();
    static const long & defaultDockOverlayHintDelay();
    static void removeDockOverlayHintDelay();
    static void setDockOverlayHintDelay(const long &v);
    static const char *docDockOverlayHintDelay();

    static const long & DockOverlayAnimationDuration();
    static const long & defaultDockOverlayAnimationDuration();
    static void removeDockOverlayAnimationDuration();
    static void setDockOverlayAnimationDuration(const long &v);
    static const char *docDockOverlayAnimationDuration();

    static const long & DockOverlayAnimationCurve();
    static const long & defaultDockOverlayAnimationCurve();
    static void removeDockOverlayAnimationCurve();
    static void setDockOverlayAnimationCurve(const long &v);
    static const char *docDockOverlayAnimationCurve();

    static const bool & DockOverlayHidePropertyViewScrollBar();
    static const bool & defaultDockOverlayHidePropertyViewScrollBar();
    static void removeDockOverlayHidePropertyViewScrollBar();
    static void setDockOverlayHidePropertyViewScrollBar(const bool &v);
    static const char *docDockOverlayHidePropertyViewScrollBar();

    static const double & EditingTransparency();
    static const double & defaultEditingTransparency();
    static void removeEditingTransparency();
    static void setEditingTransparency(const double &v);
    static const char *docEditingTransparency();

    static const double & HiddenLineTransparency();
    static const double & defaultHiddenLineTransparency();
    static void removeHiddenLineTransparency();
    static void setHiddenLineTransparency(const double &v);
    static const char *docHiddenLineTransparency();

    static const bool & HiddenLineOverrideTransparency();
    static const bool & defaultHiddenLineOverrideTransparency();
    static void removeHiddenLineOverrideTransparency();
    static void setHiddenLineOverrideTransparency(const bool &v);
    static const char *docHiddenLineOverrideTransparency();

    static const unsigned long & HiddenLineFaceColor();
    static const unsigned long & defaultHiddenLineFaceColor();
    static void removeHiddenLineFaceColor();
    static void setHiddenLineFaceColor(const unsigned long &v);
    static const char *docHiddenLineFaceColor();

    static const bool & HiddenLineOverrideFaceColor();
    static const bool & defaultHiddenLineOverrideFaceColor();
    static void removeHiddenLineOverrideFaceColor();
    static void setHiddenLineOverrideFaceColor(const bool &v);
    static const char *docHiddenLineOverrideFaceColor();

    static const unsigned long & HiddenLineColor();
    static const unsigned long & defaultHiddenLineColor();
    static void removeHiddenLineColor();
    static void setHiddenLineColor(const unsigned long &v);
    static const char *docHiddenLineColor();

    static const bool & HiddenLineOverrideColor();
    static const bool & defaultHiddenLineOverrideColor();
    static void removeHiddenLineOverrideColor();
    static void setHiddenLineOverrideColor(const bool &v);
    static const char *docHiddenLineOverrideColor();

    static const unsigned long & HiddenLineBackground();
    static const unsigned long & defaultHiddenLineBackground();
    static void removeHiddenLineBackground();
    static void setHiddenLineBackground(const unsigned long &v);
    static const char *docHiddenLineBackground();

    static const bool & HiddenLineOverrideBackground();
    static const bool & defaultHiddenLineOverrideBackground();
    static void removeHiddenLineOverrideBackground();
    static void setHiddenLineOverrideBackground(const bool &v);
    static const char *docHiddenLineOverrideBackground();

    static const bool & HiddenLineShaded();
    static const bool & defaultHiddenLineShaded();
    static void removeHiddenLineShaded();
    static void setHiddenLineShaded(const bool &v);
    static const char *docHiddenLineShaded();

    static const bool & HiddenLineShowOutline();
    static const bool & defaultHiddenLineShowOutline();
    static void removeHiddenLineShowOutline();
    static void setHiddenLineShowOutline(const bool &v);
    static const char *docHiddenLineShowOutline();

    static const bool & HiddenLinePerFaceOutline();
    static const bool & defaultHiddenLinePerFaceOutline();
    static void removeHiddenLinePerFaceOutline();
    static void setHiddenLinePerFaceOutline(const bool &v);
    static const char *docHiddenLinePerFaceOutline();

    static const double & HiddenLineWidth();
    static const double & defaultHiddenLineWidth();
    static void removeHiddenLineWidth();
    static void setHiddenLineWidth(const double &v);
    static const char *docHiddenLineWidth();

    static const double & HiddenLinePointSize();
    static const double & defaultHiddenLinePointSize();
    static void removeHiddenLinePointSize();
    static void setHiddenLinePointSize(const double &v);
    static const char *docHiddenLinePointSize();

    static const bool & HiddenLineHideSeam();
    static const bool & defaultHiddenLineHideSeam();
    static void removeHiddenLineHideSeam();
    static void setHiddenLineHideSeam(const bool &v);
    static const char *docHiddenLineHideSeam();

    static const bool & HiddenLineHideVertex();
    static const bool & defaultHiddenLineHideVertex();
    static void removeHiddenLineHideVertex();
    static void setHiddenLineHideVertex(const bool &v);
    static const char *docHiddenLineHideVertex();

    static const bool & HiddenLineHideFace();
    static const bool & defaultHiddenLineHideFace();
    static void removeHiddenLineHideFace();
    static void setHiddenLineHideFace(const bool &v);
    static const char *docHiddenLineHideFace();

    static const long & StatusMessageTimeout();
    static const long & defaultStatusMessageTimeout();
    static void removeStatusMessageTimeout();
    static void setStatusMessageTimeout(const long &v);
    static const char *docStatusMessageTimeout();

    static const bool & ShadowFlatLines();
    static const bool & defaultShadowFlatLines();
    static void removeShadowFlatLines();
    static void setShadowFlatLines(const bool &v);
    static const char *docShadowFlatLines();

    static const long & ShadowDisplayMode();
    static const long & defaultShadowDisplayMode();
    static void removeShadowDisplayMode();
    static void setShadowDisplayMode(const long &v);
    static const char *docShadowDisplayMode();

    static const bool & ShadowSpotLight();
    static const bool & defaultShadowSpotLight();
    static void removeShadowSpotLight();
    static void setShadowSpotLight(const bool &v);
    static const char *docShadowSpotLight();

    static const double & ShadowLightIntensity();
    static const double & defaultShadowLightIntensity();
    static void removeShadowLightIntensity();
    static void setShadowLightIntensity(const double &v);
    static const char *docShadowLightIntensity();

    static const double & ShadowLightDirectionX();
    static const double & defaultShadowLightDirectionX();
    static void removeShadowLightDirectionX();
    static void setShadowLightDirectionX(const double &v);
    static const char *docShadowLightDirectionX();

    static const double & ShadowLightDirectionY();
    static const double & defaultShadowLightDirectionY();
    static void removeShadowLightDirectionY();
    static void setShadowLightDirectionY(const double &v);
    static const char *docShadowLightDirectionY();

    static const double & ShadowLightDirectionZ();
    static const double & defaultShadowLightDirectionZ();
    static void removeShadowLightDirectionZ();
    static void setShadowLightDirectionZ(const double &v);
    static const char *docShadowLightDirectionZ();

    static const unsigned long & ShadowLightColor();
    static const unsigned long & defaultShadowLightColor();
    static void removeShadowLightColor();
    static void setShadowLightColor(const unsigned long &v);
    static const char *docShadowLightColor();

    static const bool & ShadowShowGround();
    static const bool & defaultShadowShowGround();
    static void removeShadowShowGround();
    static void setShadowShowGround(const bool &v);
    static const char *docShadowShowGround();

    static const bool & ShadowGroundBackFaceCull();
    static const bool & defaultShadowGroundBackFaceCull();
    static void removeShadowGroundBackFaceCull();
    static void setShadowGroundBackFaceCull(const bool &v);
    static const char *docShadowGroundBackFaceCull();

    static const double & ShadowGroundScale();
    static const double & defaultShadowGroundScale();
    static void removeShadowGroundScale();
    static void setShadowGroundScale(const double &v);
    static const char *docShadowGroundScale();

    static const unsigned long & ShadowGroundColor();
    static const unsigned long & defaultShadowGroundColor();
    static void removeShadowGroundColor();
    static void setShadowGroundColor(const unsigned long &v);
    static const char *docShadowGroundColor();

    static const std::string & ShadowGroundBumpMap();
    static const std::string & defaultShadowGroundBumpMap();
    static void removeShadowGroundBumpMap();
    static void setShadowGroundBumpMap(const std::string &v);
    static const char *docShadowGroundBumpMap();

    static const std::string & ShadowGroundTexture();
    static const std::string & defaultShadowGroundTexture();
    static void removeShadowGroundTexture();
    static void setShadowGroundTexture(const std::string &v);
    static const char *docShadowGroundTexture();

    static const double & ShadowGroundTextureSize();
    static const double & defaultShadowGroundTextureSize();
    static void removeShadowGroundTextureSize();
    static void setShadowGroundTextureSize(const double &v);
    static const char *docShadowGroundTextureSize();

    static const double & ShadowGroundTransparency();
    static const double & defaultShadowGroundTransparency();
    static void removeShadowGroundTransparency();
    static void setShadowGroundTransparency(const double &v);
    static const char *docShadowGroundTransparency();

    static const bool & ShadowGroundShading();
    static const bool & defaultShadowGroundShading();
    static void removeShadowGroundShading();
    static void setShadowGroundShading(const bool &v);
    static const char *docShadowGroundShading();

    static const bool & ShadowExtraRedraw();
    static const bool & defaultShadowExtraRedraw();
    static void removeShadowExtraRedraw();
    static void setShadowExtraRedraw(const bool &v);
    static const char *docShadowExtraRedraw();

    static const long & ShadowSmoothBorder();
    static const long & defaultShadowSmoothBorder();
    static void removeShadowSmoothBorder();
    static void setShadowSmoothBorder(const long &v);
    static const char *docShadowSmoothBorder();

    static const long & ShadowSpreadSize();
    static const long & defaultShadowSpreadSize();
    static void removeShadowSpreadSize();
    static void setShadowSpreadSize(const long &v);
    static const char *docShadowSpreadSize();

    static const long & ShadowSpreadSampleSize();
    static const long & defaultShadowSpreadSampleSize();
    static void removeShadowSpreadSampleSize();
    static void setShadowSpreadSampleSize(const long &v);
    static const char *docShadowSpreadSampleSize();

    static const double & ShadowPrecision();
    static const double & defaultShadowPrecision();
    static void removeShadowPrecision();
    static void setShadowPrecision(const double &v);
    static const char *docShadowPrecision();

    static const double & ShadowEpsilon();
    static const double & defaultShadowEpsilon();
    static void removeShadowEpsilon();
    static void setShadowEpsilon(const double &v);
    static const char *docShadowEpsilon();

    static const double & ShadowThreshold();
    static const double & defaultShadowThreshold();
    static void removeShadowThreshold();
    static void setShadowThreshold(const double &v);
    static const char *docShadowThreshold();

    static const double & ShadowBoundBoxScale();
    static const double & defaultShadowBoundBoxScale();
    static void removeShadowBoundBoxScale();
    static void setShadowBoundBoxScale(const double &v);
    static const char *docShadowBoundBoxScale();

    static const double & ShadowMaxDistance();
    static const double & defaultShadowMaxDistance();
    static void removeShadowMaxDistance();
    static void setShadowMaxDistance(const double &v);
    static const char *docShadowMaxDistance();

    static const bool & ShadowTransparentShadow();
    static const bool & defaultShadowTransparentShadow();
    static void removeShadowTransparentShadow();
    static void setShadowTransparentShadow(const bool &v);
    static const char *docShadowTransparentShadow();

    static const bool & ShadowUpdateGround();
    static const bool & defaultShadowUpdateGround();
    static void removeShadowUpdateGround();
    static void setShadowUpdateGround(const bool &v);
    static const char *docShadowUpdateGround();

    static const unsigned long & PropertyViewTimer();
    static const unsigned long & defaultPropertyViewTimer();
    static void removePropertyViewTimer();
    static void setPropertyViewTimer(const unsigned long &v);
    static const char *docPropertyViewTimer();

    static const bool & HierarchyAscend();
    static const bool & defaultHierarchyAscend();
    static void removeHierarchyAscend();
    static void setHierarchyAscend(const bool &v);
    static const char *docHierarchyAscend();

    static const long & CommandHistorySize();
    static const long & defaultCommandHistorySize();
    static void removeCommandHistorySize();
    static void setCommandHistorySize(const long &v);
    static const char *docCommandHistorySize();

    static const long & PieMenuIconSize();
    static const long & defaultPieMenuIconSize();
    static void removePieMenuIconSize();
    static void setPieMenuIconSize(const long &v);
    static const char *docPieMenuIconSize();

    static const long & PieMenuRadius();
    static const long & defaultPieMenuRadius();
    static void removePieMenuRadius();
    static void setPieMenuRadius(const long &v);
    static const char *docPieMenuRadius();

    static const long & PieMenuTriggerRadius();
    static const long & defaultPieMenuTriggerRadius();
    static void removePieMenuTriggerRadius();
    static void setPieMenuTriggerRadius(const long &v);
    static const char *docPieMenuTriggerRadius();

    static const long & PieMenuFontSize();
    static const long & defaultPieMenuFontSize();
    static void removePieMenuFontSize();
    static void setPieMenuFontSize(const long &v);
    static const char *docPieMenuFontSize();

    static const long & PieMenuTriggerDelay();
    static const long & defaultPieMenuTriggerDelay();
    static void removePieMenuTriggerDelay();
    static void setPieMenuTriggerDelay(const long &v);
    static const char *docPieMenuTriggerDelay();

    static const bool & PieMenuTriggerAction();
    static const bool & defaultPieMenuTriggerAction();
    static void removePieMenuTriggerAction();
    static void setPieMenuTriggerAction(const bool &v);
    static const char *docPieMenuTriggerAction();

    static const long & PieMenuAnimationDuration();
    static const long & defaultPieMenuAnimationDuration();
    static void removePieMenuAnimationDuration();
    static void setPieMenuAnimationDuration(const long &v);
    static const char *docPieMenuAnimationDuration();

    static const long & PieMenuAnimationCurve();
    static const long & defaultPieMenuAnimationCurve();
    static void removePieMenuAnimationCurve();
    static void setPieMenuAnimationCurve(const long &v);
    static const char *docPieMenuAnimationCurve();

    static const long & PieMenuCenterRadius();
    static const long & defaultPieMenuCenterRadius();
    static void removePieMenuCenterRadius();
    static void setPieMenuCenterRadius(const long &v);
    static const char *docPieMenuCenterRadius();

    static const bool & PieMenuPopup();
    static const bool & defaultPieMenuPopup();
    static void removePieMenuPopup();
    static void setPieMenuPopup(const bool &v);
    static const char *docPieMenuPopup();

    static const bool & StickyTaskControl();
    static const bool & defaultStickyTaskControl();
    static void removeStickyTaskControl();
    static void setStickyTaskControl(const bool &v);
    static const char *docStickyTaskControl();

    static const bool & ColorOnTop();
    static const bool & defaultColorOnTop();
    static void removeColorOnTop();
    static void setColorOnTop(const bool &v);
    static const char *docColorOnTop();

    static const bool & ColorRecompute();
    static const bool & defaultColorRecompute();
    static void removeColorRecompute();
    static void setColorRecompute(const bool &v);
    static const char *docColorRecompute();

    static const bool & AutoSortWBList();
    static const bool & defaultAutoSortWBList();
    static void removeAutoSortWBList();
    static void setAutoSortWBList(const bool &v);
    static const char *docAutoSortWBList();

    static const long & MaxCameraAnimatePeriod();
    static const long & defaultMaxCameraAnimatePeriod();
    static void removeMaxCameraAnimatePeriod();
    static void setMaxCameraAnimatePeriod(const long &v);
    static const char *docMaxCameraAnimatePeriod();

    static const bool & TaskNoWheelFocus();
    static const bool & defaultTaskNoWheelFocus();
    static void removeTaskNoWheelFocus();
    static void setTaskNoWheelFocus(const bool &v);
    static const char *docTaskNoWheelFocus();

    static const bool & GestureLongPressRotationCenter();
    static const bool & defaultGestureLongPressRotationCenter();
    static void removeGestureLongPressRotationCenter();
    static void setGestureLongPressRotationCenter(const bool &v);
    static const char *docGestureLongPressRotationCenter();

    static const bool & CheckWidgetPlacementOnRestore();
    static const bool & defaultCheckWidgetPlacementOnRestore();
    static void removeCheckWidgetPlacementOnRestore();
    static void setCheckWidgetPlacementOnRestore(const bool &v);
    static const char *docCheckWidgetPlacementOnRestore();

    static const long & TextCursorWidth();
    static const long & defaultTextCursorWidth();
    static void removeTextCursorWidth();
    static void setTextCursorWidth(const long &v);
    static const char *docTextCursorWidth();

    static void onTextCursorWidthChanged();

    static const long & PreselectionToolTipCorner();
    static const long & defaultPreselectionToolTipCorner();
    static void removePreselectionToolTipCorner();
    static void setPreselectionToolTipCorner(const long &v);
    static const char *docPreselectionToolTipCorner();

    static const long & PreselectionToolTipOffsetX();
    static const long & defaultPreselectionToolTipOffsetX();
    static void removePreselectionToolTipOffsetX();
    static void setPreselectionToolTipOffsetX(const long &v);
    static const char *docPreselectionToolTipOffsetX();

    static const long & PreselectionToolTipOffsetY();
    static const long & defaultPreselectionToolTipOffsetY();
    static void removePreselectionToolTipOffsetY();
    static void setPreselectionToolTipOffsetY(const long &v);
    static const char *docPreselectionToolTipOffsetY();

    static const long & PreselectionToolTipFontSize();
    static const long & defaultPreselectionToolTipFontSize();
    static void removePreselectionToolTipFontSize();
    static void setPreselectionToolTipFontSize(const long &v);
    static const char *docPreselectionToolTipFontSize();

    static const bool & SectionFill();
    static const bool & defaultSectionFill();
    static void removeSectionFill();
    static void setSectionFill(const bool &v);
    static const char *docSectionFill();

    static const bool & SectionFillInvert();
    static const bool & defaultSectionFillInvert();
    static void removeSectionFillInvert();
    static void setSectionFillInvert(const bool &v);
    static const char *docSectionFillInvert();

    static const bool & SectionConcave();
    static const bool & defaultSectionConcave();
    static void removeSectionConcave();
    static void setSectionConcave(const bool &v);
    static const char *docSectionConcave();

    static const bool & NoSectionOnTop();
    static const bool & defaultNoSectionOnTop();
    static void removeNoSectionOnTop();
    static void setNoSectionOnTop(const bool &v);
    static const char *docNoSectionOnTop();

    static const double & SectionHatchTextureScale();
    static const double & defaultSectionHatchTextureScale();
    static void removeSectionHatchTextureScale();
    static void setSectionHatchTextureScale(const double &v);
    static const char *docSectionHatchTextureScale();

    static const std::string & SectionHatchTexture();
    static const std::string & defaultSectionHatchTexture();
    static void removeSectionHatchTexture();
    static void setSectionHatchTexture(const std::string &v);
    static const char *docSectionHatchTexture();

    static void onSectionHatchTextureChanged();

    static const bool & SectionHatchTextureEnable();
    static const bool & defaultSectionHatchTextureEnable();
    static void removeSectionHatchTextureEnable();
    static void setSectionHatchTextureEnable(const bool &v);
    static const char *docSectionHatchTextureEnable();

    static const bool & SectionFillGroup();
    static const bool & defaultSectionFillGroup();
    static void removeSectionFillGroup();
    static void setSectionFillGroup(const bool &v);
    static const char *docSectionFillGroup();

    static const bool & ShowClipPlane();
    static const bool & defaultShowClipPlane();
    static void removeShowClipPlane();
    static void setShowClipPlane(const bool &v);
    static const char *docShowClipPlane();

    static const double & ClipPlaneSize();
    static const double & defaultClipPlaneSize();
    static void removeClipPlaneSize();
    static void setClipPlaneSize(const double &v);
    static const char *docClipPlaneSize();

    static const std::string & ClipPlaneColor();
    static const std::string & defaultClipPlaneColor();
    static void removeClipPlaneColor();
    static void setClipPlaneColor(const std::string &v);
    static const char *docClipPlaneColor();

    static const double & ClipPlaneLineWidth();
    static const double & defaultClipPlaneLineWidth();
    static void removeClipPlaneLineWidth();
    static void setClipPlaneLineWidth(const double &v);
    static const char *docClipPlaneLineWidth();

    static const bool & TransformOnTop();
    static const bool & defaultTransformOnTop();
    static void removeTransformOnTop();
    static void setTransformOnTop(const bool &v);
    static const char *docTransformOnTop();

    static const double & SelectionColorDifference();
    static const double & defaultSelectionColorDifference();
    static void removeSelectionColorDifference();
    static void setSelectionColorDifference(const double &v);
    static const char *docSelectionColorDifference();

    static const long & RenderCacheMergeCount();
    static const long & defaultRenderCacheMergeCount();
    static void removeRenderCacheMergeCount();
    static void setRenderCacheMergeCount(const long &v);
    static const char *docRenderCacheMergeCount();

    static const long & RenderCacheMergeCountMin();
    static const long & defaultRenderCacheMergeCountMin();
    static void removeRenderCacheMergeCountMin();
    static void setRenderCacheMergeCountMin(const long &v);
    static const char *docRenderCacheMergeCountMin();

    static const long & RenderCacheMergeCountMax();
    static const long & defaultRenderCacheMergeCountMax();
    static void removeRenderCacheMergeCountMax();
    static void setRenderCacheMergeCountMax(const long &v);
    static const char *docRenderCacheMergeCountMax();

    static const long & RenderCacheMergeDepthMax();
    static const long & defaultRenderCacheMergeDepthMax();
    static void removeRenderCacheMergeDepthMax();
    static void setRenderCacheMergeDepthMax(const long &v);
    static const char *docRenderCacheMergeDepthMax();

    static const long & RenderCacheMergeDepthMin();
    static const long & defaultRenderCacheMergeDepthMin();
    static void removeRenderCacheMergeDepthMin();
    static void setRenderCacheMergeDepthMin(const long &v);
    static const char *docRenderCacheMergeDepthMin();

    static const bool & ForceSolidSingleSideLighting();
    static const bool & defaultForceSolidSingleSideLighting();
    static void removeForceSolidSingleSideLighting();
    static void setForceSolidSingleSideLighting(const bool &v);
    static const char *docForceSolidSingleSideLighting();

    static const long & DefaultFontSize();
    static const long & defaultDefaultFontSize();
    static void removeDefaultFontSize();
    static void setDefaultFontSize(const long &v);
    static const char *docDefaultFontSize();

    static void onDefaultFontSizeChanged();

    static const bool & EnableTaskPanelKeyTranslate();
    static const bool & defaultEnableTaskPanelKeyTranslate();
    static void removeEnableTaskPanelKeyTranslate();
    static void setEnableTaskPanelKeyTranslate(const bool &v);
    static const char *docEnableTaskPanelKeyTranslate();

    static void onEnableTaskPanelKeyTranslateChanged();

    static const bool & EnableMenuBarCheckBox();
    static const bool & defaultEnableMenuBarCheckBox();
    static void removeEnableMenuBarCheckBox();
    static void setEnableMenuBarCheckBox(const bool &v);
    static const char *docEnableMenuBarCheckBox();

    static const bool & EnableBacklight();
    static const bool & defaultEnableBacklight();
    static void removeEnableBacklight();
    static void setEnableBacklight(const bool &v);
    static const char *docEnableBacklight();

    static const unsigned long & BacklightColor();
    static const unsigned long & defaultBacklightColor();
    static void removeBacklightColor();
    static void setBacklightColor(const unsigned long &v);
    static const char *docBacklightColor();

    static const double & BacklightIntensity();
    static const double & defaultBacklightIntensity();
    static void removeBacklightIntensity();
    static void setBacklightIntensity(const double &v);
    static const char *docBacklightIntensity();

    static const bool & OverrideSelectability();
    static const bool & defaultOverrideSelectability();
    static void removeOverrideSelectability();
    static void setOverrideSelectability(const bool &v);
    static const char *docOverrideSelectability();
//[[[end]]]

    static bool highlightIndicesOnFullSelect() {
        return ShowSelectionOnTop() && PartialHighlightOnFullSelect();
    }

    static int appDefaultFontSize();

    static void useRenderer(bool enable);
    static bool isUsingRenderer();
    static bool hiddenLineSelectionOnTop();
    static bool highlightPick();
    static void init();


/*[[[cog
ViewParams.declare_end()
]]]*/

};

} // namespace {namespace}
//[[[end]]]

#endif // GUI_VIEW_PARAMS_H
